### ISSUE TITLE
Añadir identificadores - Esteban

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#1]
agenda.xhtml
buscador_expedientes.xhtml

**Comment by estebanpw** [comment]
Hecho

**Comment by estebanpw** [comment]
lo he añadido sin querer en la rama de añadirIdentificadoresCitas o por el estilo. Nevermind XD.

**Comment by AlvaroFaure** [comment]
![bronson](https://cloud.githubusercontent.com/assets/11488816/7552095/f9a9d6d4-f6a1-11e4-9d95-3686db4dd67b.gif)

No toquéis mis ramas >:(

**Comment by estebanpw** [comment]
xDDDDDDDDDDD

**Comment by estebanpw** [comment]
Why reopen @AlvaroFaure 
Está en tu rama

**Comment by AlvaroFaure** [comment]
Te digo lo que a Felipe (y te lo digo con la siguiente cara): Espérate a que se mergee la PR.
![yo de pequeno 14 - copia](https://cloud.githubusercontent.com/assets/11488816/7596750/4fac638a-f8f0-11e4-8f42-0d5abb955ae4.jpg)
