### ISSUE TITLE
Tests en Selenium -> En la branch addUltimosId

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/SSCEntrega3#104]
Vamos a crear una asignación de tests para agilizar el proceso:

Felipe -> Tests en vista Expedientes y buscador expedientes

Haritz -> Tests navegación de páginas y login

Esteban -> tests calendario

Faure-> Tests citas

Si no os gusta os podéis cambiar(Comunicadlo plz)

**Comment by AlvaroFaure** [comment]
Lo veo bien, me quedo con las citas.

**Comment by HaritzPuerto** [comment]
#103

**Comment by HaritzPuerto** [comment]
Comprobad que estáis en el index cuando cerráis la sesión. Comprobad que tenéis un botón para cerrar la sesión SIEMPRE

**Comment by HaritzPuerto** [comment]
Voy a ayudar a Faure a hacer tests para las citas.
