### ISSUE TITLE
Cambiar el nombre que sale en la pestaña

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#110]
Como bien dijo Haritz, debería ser en todo caso SSSSCC, aunque yo pondría Servicios Sociales Comunitarios y ale. Es una tontada pero lo he visto, me he acordado y bueno, es una palabra xD Lo voy a considerar como "cambio" en las vistas y lo voy a poner en el doc, así que lo cambiamos, eh.

**Comment by HaritzPuerto** [comment]
+1. I'm on it
