### ISSUE TITLE
«¿Qué queda por hacer?» Nos preguntamos

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#111]
Terminé el informe de requisitos y Haritz lo revisó. Está perfecto para entregar.

Terminé el informe de la práctica. Haritz lo revisó. Quedan las conclusiones y estará perfecto para entregar.

Queda arreglar lo de la actualización de la tabla (si se puede).

Queda terminar con los tests.

Por favor, acabemos mañana martes y entreguemos esa misma noche. Quiero sentir EL ALIVIO.

**Comment by HaritzPuerto** [comment]
Queda #116 #112  y las PR @AlvaroFaure @FelipeSulser @steveomatic

**Comment by AlvaroFaure** [comment]
#112 terminada.

**Comment by AlvaroFaure** [comment]
Todo lo que queda está en forma de issue.
