### ISSUE TITLE
Añadir conclusiones al informe

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#116]
@steveomatic @FelipeSulser Solo queda eso. Ya he revisado todo y he añadido el trabajo futuro

**Comment by AlvaroFaure** [comment]
EL RESTO DEL DOCUMENTO ESTÁ LISTO PARA ENTREGAR, ES LO ÚNICO QUE FALTA.

**Comment by AlvaroFaure** [comment]
EL DOCUMENTO DE REQUISITOS Y EL INFORME ESTÁN LISTOS PARA ENVIAR. LOS BAJO EN PDF.
