### ISSUE TITLE
Error en Tests

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/SSCEntrega3#125]
## crearCitaConUsuario1_aAlvaroVerCalendario:

-- Peta en //form[@id='formulario_crer_cita']/table/tbody/tr[2]/td
--y tambien css=span.fc-title
## verExpedienteHaritzDesdeUsuario666UsandoMenuIzq

--Peta en link=SSCEntrega3

**Comment by HaritzPuerto** [comment]
El primero lo he borrado. El segundo ya está arreglado
