### ISSUE TITLE
Revisión archivo entregado

### ISSUE THREAD

**Issue by estebanpw** [FelipeSulser/SSCEntrega3#135]
@HaritzPuerto @FelipeSulser @AlvaroFaure 
Hay varios tests de selenium que NO tienen el formato .html, no es que esto sea incorrecto, pero a saber, el profesor usará selenium quizá para otra plataforma. Hay que ponerles el .html y resubir.

**Comment by AlvaroFaure** [comment]
Tito Faure lo tiene siempre todo controlado. Bajé la release, dividí los archivos en tres carpetas: Test Suite, Proyecto y Documentos. Releí los dos documentos, probé de nuevo la aplicación, cambié la extensión de todos los tests y los volví a pasar sobre la aplicación por asegurar que funcionaban. Y por último añadí un comentario en la entrega para dejar todo claro y que no hubiese problemas. Os pego la captura aquí:

![image](https://cloud.githubusercontent.com/assets/11488816/7824844/d568a0a8-0406-11e5-8446-8e16cdaee75a.png)

Las tres carpetas os las subí a Drive en la carpeta de ENTREGA FINAL.
Deja de hacer issues, esto ha terminado :tada:
