### ISSUE TITLE
Añadir lo que haga falta para crear la DB

### ISSUE THREAD

**Issue by estebanpw** [FelipeSulser/SSCEntrega3#14]
Persistence.xml (ya lo he puesto de mil formas y no quiere)
La database crearla con una conexión (Doesnt work either. Why?)

**Comment by estebanpw** [comment]
[SOLVED]
Con reinstalar netbeans es suficiente.

**Comment by HaritzPuerto** [comment]
Mejor aún, crear las tablas a mano con la consola que trae netbeans.
