### ISSUE TITLE
¿Cuántas instancias de cada Servlet crea un contenedor Web en memoria?

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#16]
Es una pregunta del examen del año pasado.
¿Alguien sabe la respuesta? ¿Dónde viene eso?

@FelipeSulser @steveomatic @AlvaroFaure @soutoner @fraanii94

**Comment by AlvaroFaure** [comment]
WTF. ¿Quién sabe estas cosas? En los apuntes no está y no recuerdo que se dijese en clase.

**Comment by HaritzPuerto** [comment]
Pues cayó en el examen... Voy a preguntarlo en el campus
