### ISSUE TITLE
Master me funciona pero no CambiosEstructura

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#17]
@FelipeSulser @steveomatic

**Comment by HaritzPuerto** [comment]
/home/haritz/NetBeansProjects/SSCEntrega3/SSCEntrega3-war/nbproject/build-impl.xml:1020: Warning: Could not find file /home/haritz/NetBeansProjects/SSCEntrega3/SSCEntrega3-war/${libs.javaee-api-7.0.classpath} to copy.
BUILD FAILED (total time: 2 seconds)

**Comment by HaritzPuerto** [comment]
El ejb sí compila, pero no el .war

**Comment by AlvaroFaure** [comment]
A mí me funciona perfectamente la rama de Felipe, a él obviamente también y parece que Esteban ídem. Yo propongo que mergeemos y trabajemos sobre ella y luego solucionemos el problema particular tuyo.

**Comment by HaritzPuerto** [comment]
ok debe ser problema de mi netbeans...

**Comment by AlvaroFaure** [comment]
Bueno, ya habrás visto en gitter que a mí ahora tampoco me funciona. No lo entiendo, ayer sí y hoy no. Sin cambios ni nada.
