### ISSUE TITLE
Añadir identificadores - Felipe

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#2]
expediente.xhtml
index.xhtml

**Comment by AlvaroFaure** [comment]
Espérate a que se mergee la PR
![yo de pequeno 14 - copia](https://cloud.githubusercontent.com/assets/11488816/7584173/d47c1790-f89b-11e4-9e46-902a143a45f0.jpg)

**Comment by HaritzPuerto** [comment]
Ese faure pro del github!! Por fin alguien entiende que un issue no está solucionado hasta que la solución no está en master.

**Comment by AlvaroFaure** [comment]
Ahora sí.
