### ISSUE TITLE
TO-DO GENERAL (▲▲▲ IMPORTANT ▲▲▲)

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/SSCEntrega3#24]
# TO-DO
### EJB's de todas las vistas

(Marcad si habeis acabado)
- Faure (DONE)
- Fran
- Adrián
- Esteban
- Haritz (DONE)
- Felipe (DONE)
### Conectar todas las vistas entre si con paso de mensajes entre beans

(Marcad si habeis acabado)
- Faure (DONE)
- Fran
- Adrián
- Esteban
- Haritz (DONE)
- Felipe (DONE)

**Comment by estebanpw** [comment]
@FelipeSulser  mi ejb de buscador_expedientes está ya listo salvo una cosilla, puedes probarlo? Está en mi rama. Es que mi db no funciona :(
