### ISSUE TITLE
Que alguien revise la rama EJBCrearCita

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#27]
¿Podéis deploy el ejb?

**Comment by estebanpw** [comment]
¿Te refieres a que no pete al deployear?
Yo sí puedo, la solución fue con lo que dijo felipe: Crear un nuevo JNDI en glassfish

**Comment by HaritzPuerto** [comment]
JNDI? eso para qué es? @steveomatic

**Comment by FelipeSulser** [comment]
JNDI = nombre de la conexión.
Crea otra conexión de jdbc

**Comment by HaritzPuerto** [comment]
Eso ya lo tengo. No es problema de la DB. Es problema de la inyección de dependencias.
