### ISSUE TITLE
Underline botón CERRAR SESIÓN

### ISSUE THREAD

**Issue by estebanpw** [FelipeSulser/SSCEntrega3#42]
CAMBIAR

**Comment by HaritzPuerto** [comment]
@soutoner @fraanii94

**Comment by HaritzPuerto** [comment]
Oye eso no sale siempre. @steveomatic dinos dónde sale exactamente

**Comment by soutoner** [comment]
Eso @steveomatic , te escuchamos 
![image](https://cloud.githubusercontent.com/assets/2651613/7767758/69aa2ac4-0075-11e5-9b8b-9be6eab2ecf7.png)

**Comment by HaritzPuerto** [comment]
jajajajajajjajajajajajajas

**Comment by estebanpw** [comment]
looool @soutoner 
os pongo una captura en gitter
