### ISSUE TITLE
Cambiar @GeneratedValue para que empiece a partir de n con n>=500

### ISSUE THREAD

**Issue by estebanpw** [FelipeSulser/SSCEntrega3#44]
Para que no pete al insertar y podamos hacer pruebas

**Comment by HaritzPuerto** [comment]
No sé cómo se hace. Google it! :smile:

**Comment by AlvaroFaure** [comment]
No es necesario. Nos daba problemas porque el generador automático de ID es una secuencia (inherente a cada BD) que empieza con 1 y va de 50 en 50. La primera vez que hacemos un persist en nuestra base de datos, si tenemos una cita con id=1 peta, pero la segunda vez habéis visto que no, porque mete el 51, que está libre. 

La forma de hacer lo que quieres, Esteban, es creando una secuencia en la BD y metiéndote en esto: 

![image](https://cloud.githubusercontent.com/assets/11488816/7752188/64420774-ffde-11e4-978d-378e26fd02ba.png)

Creo que no es necesario. Cuando entreguemos la aplicación el profe lo ejecutará sobre una BD vacía (obvio xd) y todas las citas se insertarán perfectamente con 1, 51, 101, 151, etc...

Y para hacer nosotros pruebas vale con que borremos todos la cita con id=1 y listo.

![image](https://cloud.githubusercontent.com/assets/11488816/7752216/8f1d8cb6-ffde-11e4-96f5-1cdda6f697f2.png)

Pero como veáis.

**Comment by HaritzPuerto** [comment]
opino como @AlvaroFaure no habrá citas cuando se lo demos al profe o si las hay, las crearemos desde la web así que no es necesario.

**Comment by FelipeSulser** [comment]
yeah, faure is right +1

**Comment by estebanpw** [comment]
ok pues CIERRO
