### ISSUE TITLE
Detectar si la conexión es lenta

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#49]
Si el usuario tiene una conexión lento, por ejemplo yo ahora en la UMA, tarda mucho en cargar la web debido al RSS. Por eso mismo quiero detectar las conexiones lentas para darle la opción al usuario de pedir que quitemos cosas pesadas como el RSS (solo quitaremos eso). Google lo hace en gmail.

http://stackoverflow.com/questions/6994061/how-to-detect-slow-internet-connections

@fraanii94 @soutoner

**Comment by estebanpw** [comment]
ESO DIJE YO Y FUI IGNORADO !!!!!!!!!!

**Comment by FelipeSulser** [comment]
Quitamos el rss y punto

**Comment by AlvaroFaure** [comment]
No, que Fran ya hizo un botón para lo que pedía Haritz. Habrá que probar si funciona y si sí vamos a quedar muy bien.

**Comment by HaritzPuerto** [comment]
@FelipeSulser  
#ESTO NO SE PUEDE QUITAR. 
Es una buena idea para diferenciarnos. Chicano NO ha dicho que esté mal, así que se mantiene. Además, el año pasado se hizo, así que ahora nos toca mejorar lo que se hizo y eso es añadir ese botón. Creo que Fran me dijo que sabía hacerlo

**Comment by AlvaroFaure** [comment]
¿Pero no leéis el WhatsApp? xD Fran pasó un vídeo ayer enseñando el botón, que ya lo había hecho, solo que no podía probar bien si funcionaba porque su conexión precisamente no era lenta.

**Comment by HaritzPuerto** [comment]
@fraanii94 ¿Cómo lo llevas?

**Comment by AlvaroFaure** [comment]
@HaritzPuerto y yo hemos decidido que a estas alturas prescindimos ya de esto. La aplicación está terminada y meter el botón puede suponer nuevos quebraderos de cabeza, especialmente porque está hecho sobre una versión muy antigua de la aplicación (estos días hemos hecho infinitos cambios). No podemos estar esperando más, tenemos que hacer tests con la aplicación terminada y quedan 2 días.
