### ISSUE TITLE
Errores (Elegid el que queráis corregir)

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/SSCEntrega3#53]
Viendo los errores desde la consola de Glassfish pongo aqui lista de errores:

2) Si se introduce familiar, intervención etc en expediente.xhtml NO SE ACTUALIZA ( pero se inserta en la base de datos).
Si volvemos a loguearnos ya sí se actualiza.

**Comment by estebanpw** [comment]
ME QUEDO con 1) En buscador expedientes hay un NULLPOINTEREXCEPTION cuando le damos al botón de buscar expedientes.

ASIGNEE TO STEVE

**Comment by estebanpw** [comment]
[FIXED ERROR 1] @FelipeSulser
