### ISSUE TITLE
Cambios del proyecto

### ISSUE THREAD

**Issue by FelipeSulser** [FelipeSulser/SSCEntrega3#6]
A continuación os explico la estructura del proyecto.

Módulo EJB: 
- entidades JPA
- EJBeans

Módulo war:
-Controlador ( con ejb inyectados)
- Vistas

NADA DE DAO ya, el dao solo sirve para una aplicación web.
en una empresarial el EJB es lo que hace las veces de DAO.

**Comment by AlvaroFaure** [comment]
Esto es closeable, ¿no? A estas alturas... xD
