### ISSUE TITLE
Lugar añadir intervenciones

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#60]
Ahora mismo está en expediente pero creo que debería estar en ver cita, así nos ahorraríamos el problema de tener que insertar cita.id para crear una intervención.

**Comment by AlvaroFaure** [comment]
Yo opino igual.

**Comment by AlvaroFaure** [comment]
¿Esto al final se va a hacer?

**Comment by HaritzPuerto** [comment]
Depende de cómo vayamos. Si hoy está todo casi listo, sí. Me puedo ocupar yo.
