### ISSUE TITLE
Cambiar el estado de la cita

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#62]
Debe poderse modificar ese campo (¿y otros campos también?). Que alguien que controle más que yo de JSF añada un desplegable o algo así que permita actualizar el estado llamando a setEstado() de controladorCita.

**Comment by HaritzPuerto** [comment]
¿Qué otras cosas quieres modificar? Yo no recuerdo que haya nada que modificar

**Comment by AlvaroFaure** [comment]
Yo personalmente no quiero modificar nada, preguntaba en general por si creíais que se podría modificar el comentario sobre la cita, la fecha, etc.
