### ISSUE TITLE
Borrar cita con id=1 del dataSet y crear un script que genere todo

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#67]
Voy a evitaros futuros errores y voy a guardar todo (tablas y datos) en un mismo script para que, con ejecutarlo, nos genere todo al profesor (si hace falta) y a nosotros cuando nos haga falta (basta con copypastear el contenido y darle al botón de ejecutar todo).

NO USÉIS MÁS EL SCRIPT Y EL DATASET QUE HAY, USAD ESTE QUE SE LLAMA scriptTotal.sql

**Comment by estebanpw** [comment]
Deja los 2 que había y añade ese. Ya se borrarán más tarde.

Me gusta tener esos dos separados.

**Comment by AlvaroFaure** [comment]
Lo hice, están las tres cosas, pero recordad que cuando hagáis cambios o lo hacéis en el pequeño y el total o lo hacéis en el total, nunca dejéis el total desactualizado.
