### ISSUE TITLE
Borrar DAO

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#86]

**Comment by AlvaroFaure** [comment]
aka Borrar todos los archivos del paquete DAO.
Pregunta: ¿Cómo se hace eso en github? Porque yo he tratado de "eliminar" archivos más de una vez y lo que hace creo que es ignorarme, no considera que haya hecho cambios. Me lo había asignado pero me lo desasigno, no sé cómo hacerlo (igual luego es una tontería).
