### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by HaritzPuerto** [FelipeSulser/SSCEntrega3#87]
```
Warning:   JSF1091: No mime type could be found for file fonts/glyphicons-halflings-regular.woff.  To resolve this, add a mime-type mapping to the applications web.xml.
```

**Comment by AlvaroFaure** [comment]
El profesor nos dijo que los errores gordos eran los que teníamos que mirar. Una warning es una advertencia que puede no significar nada (de hecho nos dijo algo así como "los errores, no las advertencias que ya sabéis que da Glassfish a menudo). Yo no le haría caso.
