### ISSUE TITLE
ERROR al añadir vivienda en Expediente

### ISSUE THREAD

**Issue by AlvaroFaure** [FelipeSulser/SSCEntrega3#98]
Aquí tenéis toda la traza: 

![image](https://cloud.githubusercontent.com/assets/11488816/7788952/da5292b2-024f-11e5-877c-97fa08229a5f.png)
![image](https://cloud.githubusercontent.com/assets/11488816/7788954/e40d8e4c-024f-11e5-9ca6-0e4eb6dadb72.png)
![image](https://cloud.githubusercontent.com/assets/11488816/7788956/f26f41c4-024f-11e5-921f-db1a4ab362e6.png)
![image](https://cloud.githubusercontent.com/assets/11488816/7788958/fc0935d2-024f-11e5-8e73-a605481e8d0e.png)

Había introducido estos valores en el expediente de id=1
![image](https://cloud.githubusercontent.com/assets/11488816/7788961/0e138372-0250-11e5-85d5-5134c79daddd.png)

**Comment by HaritzPuerto** [comment]
Eso es porque el propietario es null ya que se llama a la otra relación (una vivienda tiene dos relaciones, propietario (residencia actual) NOT NULL, y pertecene). Podemos quitar una de esas relaciones o añadir un botón para indicar qué tipo de vivienda es.

**Comment by AlvaroFaure** [comment]
El fallo es el siguiente: Estamos creando una vivienda y estamos llamando al método que le dice "eres vivienda principal de este expediente". ¿Por qué falla? Porque es OPCIONAL que sea vivienda principal de algún expediente, pero es OBLIGATORIO que lo sea de algún otro expediente y no se lo estamos diciendo.
